version: "3.1"

volumes:
    postgres:
        external: true

services:
    postgres:
        image: postgres:alpine
        volumes:
          - postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=battle
          - POSTGRES_PASSWORD=moose
          - POSTGRES_DB=chess
        ports:
         - "5432:5432"
    go_api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/go/src/api
        ports:
            - "8080:8080"
        depends_on:
            - postgres
